version: '2'
services:
  memcached:
    image: memcached:latest
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keystone
      MYSQL_USER: keystone
      MYSQL_PASSWORD: keystone
  keystone:
    build: .
    environment:
      OS_BOOTSTRAP_USERNAME: admin
      OS_BOOTSTRAP_PASSWORD: password
      OS_BOOTSTRAP_PROJECT_NAME: admin
      OS_BOOTSTRAP_ROLE_NAME: admin
      OS_BOOTSTRAP_SERVICE_NAME: keystone
      OS_BOOTSTRAP_PUBLIC_URL: http://127.0.0.1:5000/
      OS_BOOTSTRAP_INTERNAL_URL: http://127.0.0.1:5000/
      OS_BOOTSTRAP_ADMIN_URL: http://127.0.0.1:35357/
      OS_BOOTSTRAP_REGION_ID: RegionOne
    ports:
      - 5000:5000
      - 35357:35357
    volumes:
      - "${KEYSTONE_DIR}:/opt/keystone"
      - "${KEYSTONEAUTH_DIR}:/opt/keystoneauth"
      - "${KEYSTONEMIDDLEWARE_DIR}:/opt/keystonemiddleware"
    depends_on:
      - mariadb
      - memcached
